homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 42.656
  longitude: -71.3049
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 27
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York


# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password

# Checks for available updates
updater:


# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:
 # platform: yr

# Nest

nest: 
 client_id: !secret nest_client_id
 client_secret: !secret nest_client_secret

climate:
  platform: nest

sensor:
  - platform: openweathermap
    api_key: !secret openweathermap_key
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - humidity
      - clouds
      - rain
      - snow

light:
  platform: hue
  host: 192.168.10.78

emulated_hue:
  host_ip: 192.168.10.84
  
digital_ocean:
  access_token: !secret digital_ocean_token

# IFTTT
ifttt:
  key: !secret ifttt_key

# Pushbullet
notify:
    platform: pushbullet
    api_key: !secret pushbullet_key
    name: PushBullet

#device_tracker:
 # - platform: unifi
  #  host: 192.168.10.81
   # username: admin
    #password: !secret unifi_pw

# Frontpoint

#alarm_control_panel:
 # platform: alarmdotcom
  #username: !secret alarmdotcom_user
  #password: !secret alarmdotcom_pw

# Switches

wemo:

switch:

#  - platform: tplink
 #   host: 192.168.10.26
  #  name: Christmas Tree

  #- platform: tplink
  #  host: 192.168.10.150
  #  name: Christmas Lights

  - platform: tplink
    host: 192.168.10.173
    name: Workbench

group:
 #indoor_christmas_lights:
  #name: Christmas Lights Inside
  #view: yes
  #entities: 
  # - switch.christmas_tree
  # - switch.christmas_lights
  # - switch.leg_lamp
  # - switch.table_lights

 all_dining_room:
   - light.dining_room_ceiling
   - light.dining_room_fan


 outside_door_lights:
   - light.front_door
   - light.back_door
   - light.lamp_post

lutron_caseta:
    host: 192.168.10.83
    username: lutron
    password: integration

#camera:
 # platform: foscam
  #ip: 192.168.10.180
  #username: admin
  #password: XOnZvbs1f8zZ
  #name: Kaylee Bedroom

# Kodi Living Room
#media_player:
 # - platform: kodi
  #  host: http://192.168.10.71
   # name: Kodi Living Room
    #username: kodi
    #password: !secret kodi_pw

remote:
  - platform: harmony
    name: Harmony
    host: 192.168.10.163

zwave:
  usb_path: /dev/ttyACM0

###	kodi	###
#media_player: !include_dir_list media_player

###	Scene	###
#scene: !include_dir_list scenes

###  Automation  ###
automation: !include_dir_list automation
#automation: !include_dir_list christmas_automation
