homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 42.656
  longitude: -71.3049
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 27
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

config:
# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password

system_log:

# Checks for available updates
updater:


# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:
 # platform: yr

# Nest

nest: 
 client_id: !secret nest_client_id
 client_secret: !secret nest_client_secret

climate:
  platform: nest

sensor:
  - platform: openweathermap
    api_key: !secret openweathermap_key
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - humidity
      - clouds
      - rain
      - snow
  - platform: nzbget
    host: galactica.fureynet.intranet
    username: nzbget
    password: admin
    monitored_variables:
      - download_rate
      - average_download_rate
      - free_disk_space
      - uptime

light:
  platform: hue
  host: 192.168.10.78

emulated_hue:
  host_ip: 192.168.10.84
  
digital_ocean:
  access_token: !secret digital_ocean_token

# IFTTT
ifttt:
  key: !secret ifttt_key

# Pushbullet
notify:
    platform: pushbullet
    api_key: !secret pushbullet_key
    name: PushBullet

ios:

#device_tracker:
 #  - platform: tile
  #   username: shaun@fureynet.com
   #  password: !secret tile_pw

# Frontpoint

alarm_control_panel:
  platform: alarmdotcom
  username: !secret alarmdotcom_user
  password: !secret alarmdotcom_pw

# Switches

wemo:

switch:

#  - platform: tplink
#    host: 192.168.10.171 #50:c7:bf:04:4b:7e
#    name: Christmas Table

  - platform: tplink
    host: 192.168.10.172 #50:c7:bf:04:4f:01
    name: Sump Pump

#  - platform: tplink
#    host: 192.168.10.177 #50:c7:bf:bf:9c:8e
#    name: Christmas Houses

  - platform: tplink
    host: 192.168.10.173 #50:c7:bf:17:b2:c2
    name: Workbench Light

  - platform: tplink
    host: 192.168.10.178 #50:c7:bf:b2:37:5e
    name: Nerdsense Studio

#  - platform: tplink
#    host: 192.168.10.90 #70:4f:57:97:2f:af
#    name: Christmas Tree
  
#  - platform: tplink
#    host: 192.168.10.91 #70:4f:57:9c:ad:57
#    name: Kitchen Christmas Lights
 
# Lutron Caseta -- Password cannot be stored in a secrets file
lutron_caseta:
    host: 192.168.10.83
    keyfile: caseta.key
    certfile: caseta.crt
    ca_certs: caseta-bridge.crt

mycroft:
  host: 192.168.10.88
#notify:

remote:
  - platform: harmony
    name: Harmony
    host: 192.168.10.163

#Symlink to 99-USB UDEV Rules
zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_network_key

#splunk:
 # token: 19517d93-639f-4e18-805a-caa7ad56aeb3
  #host: 172.16.5.29
 
###	kodi	###
media_player: !include_dir_list media_player

##Vizio##
#media_player:
 # - platform: vizio
  #  host: 192.168.10.62
   # access_token: yjr30azbll
###	Scene	###
scene: !include_dir_list scenes

group: !include_dir_merge_named groups
###  Automation  ###
automation: !include_dir_list automation
#automation: !include_dir_list christmas_automation
